### ISSUE TITLE
How do you think I should go about saving and loading with this?

### ISSUE THREAD

**Issue by bonkitywonk** [Gatix1/listinv#1] opened 2024-07-22 06:30 UTC
I tried to save the inventory array in a resource but i just got bombarded with errors.

**Comment by Gatix1** [comment] 2024-07-22 09:01
hi, i actually have no idea, i forgot everything after such a long time, but you can send me the screenshots of the errors you get and maybe ill see what the problem might be

**Comment by bonkitywonk** [comment] 2024-07-22 09:33
> hi, i actually have no idea, i forgot everything after such a long time, but you can send me the screenshots of the errors you get and maybe ill see what the problem might be

Hi, thanks for responding so fast!

This is what I changed
---------------------------------------

![Screenshot 2024-07-22 051732](https://github.com/user-attachments/assets/7ad89feb-e4bf-4b2a-80d2-5221d9daffd5)

![Screenshot 2024-07-22 051805](https://github.com/user-attachments/assets/d4612e22-09a5-4e52-8fcc-7588014b5695)


This is the resource that I added
-------------------------------------------

![Screenshot 2024-07-22 051824](https://github.com/user-attachments/assets/f7afd4b0-6ea8-4218-8758-8ea5d71479de)

And these are the errors that I'm getting
---------------------------------------------
![Screenshot 2024-07-22 052344](https://github.com/user-attachments/assets/bd2c4945-d516-48cd-b852-12c2fd1c89e3)


![Screenshot 2024-07-22 052703](https://github.com/user-attachments/assets/efda174d-673d-4b00-ab1f-803114c1694a)

Something worth mentioning is that I also renamed every instance of inventory to playerData.inventory since I took that variable and put it in playerData

I can't tell if there is a simple solution and im just being dumb as i'm new to gdscript and godot as a whole but i'd really appreciate if you could help out.

Thanks

**Comment by Gatix1** [comment] 2024-07-23 07:55
i will try to implement the same thing today and respond with a solution

**Comment by Gatix1** [comment] 2024-07-23 09:09
so i already figured out a few things, firstly idk why, but it doesnt create user://save/ path when saving, i think you can try creating save dir in user:// manually, i tried saving just as PlayerSave.tres in local dir, and it worked, but there is one more issue which i cant solve, because each item is a resource, and it saves only the playerData resource, there is a problem, the inner resources used (items) dont save properly, and the quantity is 1 after saving, every field is setted on default value, so maybe you can come up with some solution for this, maybe keeping inventory items as dicts and not resources

**Comment by Gatix1** [comment] 2024-07-23 09:10
if you didnt really understand what i said no worries, you can ask me here and i will go into details, but as i said i didnt really solve the issue, just found the cause of it

**Comment by bonkitywonk** [comment] 2024-07-23 09:26
> if you didnt really understand what i said no worries, you can ask me here and i will go into details, but as i said i didnt really solve the issue, just found the cause of it

Yea after trying for a little while today, I eventually got the errors to go away but it just wasn't really saving and loading things properly. After a bit of research I also came to the conclusion that I somehow needed to use a dictionary but I don't really know how to import things into dictionaries or where to even start to be honest.

If you could go into more detail or even just point me in the right direction I would really appreciate it.

**Comment by Gatix1** [comment] 2024-07-23 13:15
Sure, i'm gonna try implement a system based on dictionaries inside of the resource, i think that might work. Will let you know with the code attached when it will be done. I'll try to finish till tomorrow, so keep in touch.

**Comment by Gatix1** [comment] 2024-07-23 13:31
Hi again, i came up with a solution, you still use items as resources in this case, the difference is just you save them as dictionaries in the playerData resource, and everything works fine. The code might be a bit confusing, but its a good base as it works with no bugs. I uploaded the new code in the same repo, but on the "saving" branch, you can check it.

**Comment by bonkitywonk** [comment] 2024-07-23 18:35
> Hi again, i came up with a solution, you still use items as resources in this case, the difference is just you save them as dictionaries in the playerData resource, and everything works fine. The code might be a bit confusing, but its a good base as it works with no bugs. I uploaded the new code in the same repo, but on the "saving" branch, you can check it.

Sorry for responding a bit late. When I last responded to you it was 5am for me lol.

Thanks again for taking time out of your day to do this 👍

**Comment by Gatix1** [comment] 2024-07-24 05:59
no problem, if there is any other problem that appears just open a new issue here, im gonna close this one. Good luck on the project

**Closed as completed by Gatix1** 2024-07-24 05:59 UTC
